# there are 2 db types: mysql or mongodb
pl:
  pawsko:
    toolroom:
      database: mongodb

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/tools
    username: root
    password: coderslab
  security:
    user:
      name: admin
      password: admin
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ToolRoom
springdoc:
  swagger-ui:
    default-models-expand-depth: -1