logging:
  level:
    root: ERROR
    pl:
      pawsko:
        toolroom: DEBUG
  file:
    name: ToolRoomApp.log
    path: \

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/tools
    username: root
    password: coderslab
  security:
    user:
      name: admin
      password: admin
springdoc:
  swagger-ui:
    default-models-expand-depth: -1